packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - tsx@4.23.6
  - '@clerk/backend@3.15.1'
  - '@clerk/nextjs@7.6.5'
  - '@clerk/react@6.12.11'
  - '@clerk/shared@4.26.0'

onlyBuiltDependencies:
  - sharp
